#!/usr/bin/env bash
# 部署到 github pages 脚本

# 错误时终止脚本
set -e

# 删除打包文件夹
rm -rf public

# 打包
hugo -t puff

# CNAME
# 无须复制，hugo 打包会自动复制
# cp CNAME public/

# 进入打包文件夹
cd public

# Git init & add files
git init
git branch -m master gh-pages
git add -A

# Git commit changes
msg="building site `date +%F`"
if [ $# -eq 1 ]
  then msg="$1"
fi
git commit -m "$msg"

# 推送到 github
git remote add origin git@github.com:stuarthua/stuarthua.github.io.git
# git push --set-upstream origin gh-pages
git push -u origin gh-pages -f

# 回到原文件夹
cd ..
